language: scala

scala:
  - 2.12.2
  - 2.11.11
  - 2.10.0

env:
  - JDK=oraclejdk8
  - JDK=openjdk6

before_script:
  - jdk_switcher use $JDK

matrix:
  # scalac 2.10.0 fails with java 8
  # scalac 2.12.1 requires java 8
  exclude:
    - scala: 2.10.0
      env: JDK=oraclejdk8
    - scala: 2.12.2
      env: JDK=openjdk6
